// Navigation manifest — maps screens to routes for the screen-preview router shell.
// The agent can read/write navigation.json to control routing between screens.

import { readFile, writeFile, readDir, isNotFoundError } from "@/lib/ipc";

export interface NavScreen {
  id: string;
  path: string;
  title: string;
}

export interface Navigation {
  defaultScreen: string;
  screens: NavScreen[];
}

const NAVIGATION_FILE = "navigation.json";

function defaultNav(): Navigation {
  return { defaultScreen: "", screens: [] };
}

export async function loadNavigation(projectDir: string): Promise<Navigation> {
  try {
    const raw = await readFile(`${projectDir}/${NAVIGATION_FILE}`);
    const parsed = JSON.parse(raw) as unknown;
    if (typeof parsed !== "object" || parsed === null || !("screens" in parsed)) {
      throw new Error(`navigation.json has unexpected shape`);
    }
    return parsed as Navigation;
  } catch (e) {
    if (isNotFoundError(e)) return defaultNav();
    throw e;
  }
}

export async function saveNavigation(projectDir: string, nav: Navigation): Promise<void> {
  await writeFile(`${projectDir}/${NAVIGATION_FILE}`, JSON.stringify(nav, null, 2));
}

export async function addScreenToNavigation(projectDir: string, screenId: string): Promise<void> {
  const nav = await loadNavigation(projectDir);
  if (nav.screens.some((s) => s.id === screenId)) return;
  nav.screens.push({
    id: screenId,
    path: `/${screenId}`,
    title: screenId.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
  });
  if (!nav.defaultScreen) nav.defaultScreen = screenId;
  await saveNavigation(projectDir, nav);
}

export async function removeScreenFromNavigation(projectDir: string, screenId: string): Promise<void> {
  const nav = await loadNavigation(projectDir);
  nav.screens = nav.screens.filter((s) => s.id !== screenId);
  if (nav.defaultScreen === screenId) {
    nav.defaultScreen = nav.screens[0]?.id ?? "";
  }
  await saveNavigation(projectDir, nav);
}

export async function renameScreenInNavigation(projectDir: string, oldId: string, newId: string): Promise<void> {
  const nav = await loadNavigation(projectDir);
  const screen = nav.screens.find((s) => s.id === oldId);
  if (screen) {
    screen.id = newId;
    screen.path = `/${newId}`;
    screen.title = newId.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  }
  if (nav.defaultScreen === oldId) nav.defaultScreen = newId;
  await saveNavigation(projectDir, nav);
}

/**
 * Write screen-preview/src/routes.ts from current screens in navigation.json.
 * Called whenever screens are created, deleted, or renamed.
 * Uses a symlink screen-preview/src/screens → ../../../screens/ set up at scaffold time.
 */
export async function syncScreenPreviewRoutes(projectDir: string): Promise<void> {
  const screenPreviewDir = `${projectDir}/screen-preview`;

  // Discover all screens from the filesystem (source of truth)
  let screenEntries: Array<{ name: string }> = [];
  try {
    const entries = await readDir(`${projectDir}/screens`);
    screenEntries = entries.filter((e) => e.is_dir);
  } catch (e) {
    if (!isNotFoundError(e)) throw e;
  }

  const nav = await loadNavigation(projectDir);
  const navById = new Map(nav.screens.map((s) => [s.id, s]));

  // Build routes from filesystem — use nav for path/title, fall back to defaults
  const routes = screenEntries.map((entry) => {
    const navEntry = navById.get(entry.name);
    return {
      id: entry.name,
      path: navEntry?.path ?? `/${entry.name}`,
    };
  });

  const defaultPath = nav.defaultScreen
    ? (navById.get(nav.defaultScreen)?.path ?? routes[0]?.path ?? "/")
    : routes[0]?.path ?? "/";

  if (routes.length === 0) {
    await writeFile(
      `${screenPreviewDir}/src/routes.ts`,
      `// Auto-generated by Prototyper — do not edit manually.\nimport type { ComponentType } from 'react';\nexport const routes: Array<{ path: string; component: ComponentType }> = [];\nexport const defaultPath = "/";\n`
    );
    return;
  }

  const imports = routes
    .map((r, i) => `import Screen${i} from '@/screens/${r.id}/screen';`)
    .join("\n");

  const routeArray = routes
    .map((r, i) => `  { path: "${r.path}", component: Screen${i} },`)
    .join("\n");

  const content = `// Auto-generated by Prototyper — do not edit manually.\n${imports}\n\nexport const routes = [\n${routeArray}\n];\n\nexport const defaultPath = "${defaultPath}";\n`;

  await writeFile(`${screenPreviewDir}/src/routes.ts`, content);
}
