// ─── Pre-configured API templates shown in the sidebar dropdown ──────────────

import type { SavedApi } from "./types";

export type ApiTemplate = Omit<SavedApi, "id" | "history"> & { description: string };

export const API_TEMPLATES: ApiTemplate[] = [
  {
    name: "OpenWeatherMap — Current Weather",
    method: "GET",
    url: "https://api.openweathermap.org/data/2.5/weather?lat=51.51&lon=-0.13&units=metric&appid={{OPENWEATHERMAP_KEY}}",
    headersText: "{}",
    body: "",
    authType: "none",
    authToken: "", authHeaderName: "X-API-Key", authUsername: "", authPassword: "",
    authTokenUrl: "", authClientId: "", authClientSecret: "",
    proxyPath: "/api/weather",
    description: "Real-time weather (London). Free key at openweathermap.org → add OPENWEATHERMAP_KEY to Keys",
  },
  {
    name: "OpenWeatherMap — Forecast",
    method: "GET",
    url: "https://api.openweathermap.org/data/2.5/forecast?lat=51.51&lon=-0.13&cnt=8&units=metric&appid={{OPENWEATHERMAP_KEY}}",
    headersText: "{}",
    body: "",
    authType: "none",
    authToken: "", authHeaderName: "X-API-Key", authUsername: "", authPassword: "",
    authTokenUrl: "", authClientId: "", authClientSecret: "",
    proxyPath: "/api/weather",
    description: "5-day / 3-hour forecast (London). Same key as current weather.",
  },
  {
    name: "GitHub — Search Repos",
    method: "GET",
    url: "https://api.github.com/search/repositories?q=react&sort=stars",
    headersText: JSON.stringify({ "User-Agent": "Prototyper", "Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28" }, null, 2),
    body: "",
    authType: "none",
    authToken: "", authHeaderName: "X-API-Key", authUsername: "", authPassword: "",
    authTokenUrl: "", authClientId: "", authClientSecret: "",
    proxyPath: "/api/github",
    description: "Search public repositories. No API key needed.",
  },
  {
    name: "GitHub — User Profile",
    method: "GET",
    url: "https://api.github.com/users/octocat",
    headersText: JSON.stringify({ "User-Agent": "Prototyper", "Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28" }, null, 2),
    body: "",
    authType: "none",
    authToken: "", authHeaderName: "X-API-Key", authUsername: "", authPassword: "",
    authTokenUrl: "", authClientId: "", authClientSecret: "",
    proxyPath: "/api/github",
    description: "Fetch any GitHub user profile. No key needed.",
  },
  {
    name: "JSONPlaceholder — Posts",
    method: "GET",
    url: "https://jsonplaceholder.typicode.com/posts",
    headersText: "{}",
    body: "",
    authType: "none",
    authToken: "", authHeaderName: "X-API-Key", authUsername: "", authPassword: "",
    authTokenUrl: "", authClientId: "", authClientSecret: "",
    proxyPath: "/api/fake",
    description: "Fake REST API for prototyping. Always works, no key needed.",
  },
  {
    name: "JSONPlaceholder — Users",
    method: "GET",
    url: "https://jsonplaceholder.typicode.com/users",
    headersText: "{}",
    body: "",
    authType: "none",
    authToken: "", authHeaderName: "X-API-Key", authUsername: "", authPassword: "",
    authTokenUrl: "", authClientId: "", authClientSecret: "",
    proxyPath: "/api/fake",
    description: "Fake users list with name, email, address fields.",
  },
];
