/**
 * E2E tests for screen generation.
 *
 * Each test:
 *  1. Calls minimax-m2.5 via Ollama cloud with the real system prompt
 *  2. Passes real tsc/lint/build output back to the model so self-correction is exercised
 *  3. Writes generated code to screen-preview/src/screens/e2e-test/screen.tsx
 *  4. Patches routes.ts to expose /e2e-test as the default route
 *  5. Runs tsc, eslint, and esbuild on the final output
 *  6. Starts the Vite dev server, opens in Playwright, captures a screenshot
 *  7. Asserts: no React console errors, root has content, expected DOM elements present,
 *     screenshot is non-blank
 *  8. Saves screenshot artifact, restores routes.ts, and removes the test screen dir
 */

import { describe, it, expect, beforeAll, afterEach } from "vitest";
import fs from "node:fs/promises";
import path from "node:path";
import {
  type GenerationToolContext,
  generate,
  resolveExtraFileDests,
  requireTestProjectDir,
  screenPreviewDir,
  runFileTypecheck,
  runLint,
  filterLintOutput,
  runFileBuild,
  startDevServer,
  captureRender,
  analyzeScreenshot,
  saveSnapshot,
  snapshotDir,
  restoreFile,
} from "./helpers";
import { getScreenNewPrompt, getScreenUpdatePrompt } from "@/lib/prompts/screens";
import { outputFilePathSection } from "@/lib/prompts/shared";

// ─── Setup ────────────────────────────────────────────────────────────────────

let projectDir: string;
let appDataDir: string;
let previewDir: string;
let testScreenDir: string;
let testScreenPath: string;
let routesPath: string;
let originalRoutesTsx: string;
let writtenExtras: string[] = [];

const BASE_PORT = 4300;
let portOffset = 0;

beforeAll(async () => {
  projectDir = await requireTestProjectDir();
  appDataDir = path.join(projectDir, "..", "..");
  previewDir = screenPreviewDir(projectDir);
  testScreenDir = path.join(previewDir, "src", "screens", "e2e-test");
  testScreenPath = path.join(testScreenDir, "screen.tsx");
  routesPath = path.join(previewDir, "src", "routes.ts");

  const tscBin = path.join(previewDir, "node_modules", ".bin", "tsc");
  await fs.access(tscBin).catch(() => {
    throw new Error(
      `screen-preview is not scaffolded at ${previewDir}. ` +
        "Open the Prototyper app and scaffold the project first.",
    );
  });

  originalRoutesTsx = await fs.readFile(routesPath, "utf8");
});

afterEach(async () => {
  await restoreFile(routesPath, originalRoutesTsx);
  await fs.rm(testScreenDir, { recursive: true, force: true });
  await Promise.all(writtenExtras.map((p) => fs.rm(p, { force: true })));
  writtenExtras = [];
});

// ─── Helpers ──────────────────────────────────────────────────────────────────

function fakeOutputPath(projectId: string) {
  return `projects/${projectId}/screens/e2e-test/screen.tsx`;
}

const TOOL_CONTEXT: GenerationToolContext = {
  get previewDir() {
    return previewDir;
  },
  primaryRelPath: "src/screens/e2e-test/screen.tsx",
};

async function patchRoutesTs() {
  const patched = [
    "// Auto-generated by Prototyper — do not edit manually.",
    "import E2ETestScreen from '@/screens/e2e-test/screen';",
    "export const routes = [{ path: '/e2e-test', component: E2ETestScreen }];",
    "export const defaultPath = '/e2e-test';",
  ].join("\n");
  await fs.writeFile(routesPath, patched, "utf8");
}

async function generateWriteAndValidate(
  testLabel: string,
  userPrompt: string,
  systemPrompt: string,
  expectedSelectors: string[] = [],
) {
  const { primaryContent, extraFiles } = await generate(
    systemPrompt,
    userPrompt,
    12,
    TOOL_CONTEXT,
  );
  expect(primaryContent, "Model did not call write_file — no code produced").not.toBeNull();

  for (const [relPath, content] of Object.entries(extraFiles)) {
    if (content === primaryContent) continue;
    for (const dest of resolveExtraFileDests(relPath, appDataDir, projectDir, previewDir)) {
      await fs.mkdir(path.dirname(dest), { recursive: true });
      await fs.writeFile(dest, content, "utf8");
      writtenExtras.push(dest);
    }
  }

  await fs.mkdir(testScreenDir, { recursive: true });
  await fs.writeFile(testScreenPath, primaryContent!, "utf8");
  await patchRoutesTs();

  const tscOut = runFileTypecheck(previewDir, "src/screens/e2e-test/screen.tsx");
  expect(tscOut, `TypeScript errors in generated screen:\n${tscOut}`).toBe("");

  const lintOut = filterLintOutput(runLint(previewDir, "src/screens/e2e-test/screen.tsx"));
  expect(lintOut, `ESLint errors in generated screen:\n${lintOut}`).toBe("");

  runFileBuild(previewDir, "src/screens/e2e-test/screen.tsx");

  const port = BASE_PORT + portOffset++;
  const server = await startDevServer(previewDir, port);
  try {
    const { screenshot, consoleErrors, hasRootContent, missingSelectors } =
      await captureRender(server.url, expectedSelectors);

    const errors = consoleErrors.filter(
      (e) => !e.includes("favicon") && !e.includes("DevTools"),
    );
    expect(errors, `React console errors during render:\n${errors.join("\n")}`).toHaveLength(0);
    expect(hasRootContent, "React root rendered empty content").toBe(true);

    expect(
      missingSelectors,
      `Generated screen missing expected DOM elements:\n${missingSelectors.join("\n")}`,
    ).toHaveLength(0);

    const { nonWhiteRatio } = analyzeScreenshot(screenshot);
    expect(
      nonWhiteRatio,
      `Screenshot for "${testLabel}" appears blank (${(nonWhiteRatio * 100).toFixed(1)}% non-white pixels)`,
    ).toBeGreaterThan(0.02);

    const snapshotPath = await saveSnapshot(testLabel, screenshot, snapshotDir());
    console.log(`  snapshot: ${snapshotPath}`);
  } finally {
    server.stop();
  }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe("screen generation E2E", () => {
  it(
    "generates a dashboard screen with no type, lint, or build errors and renders",
    async () => {
      const projectId = path.basename(projectDir);
      await generateWriteAndValidate(
        "screen-dashboard",
        "Build a SaaS analytics dashboard with a sidebar nav (Dashboard, Analytics, Users, Settings), top header with search and user avatar, and main area with 4 KPI cards, a bar chart placeholder, and a recent-activity list.",
        getScreenNewPrompt("lucide") + outputFilePathSection(fakeOutputPath(projectId)),
        ["nav, [role='navigation'], aside"],
      );
    },
    240_000,
  );

  it(
    "generates an e-commerce product listing screen with no type, lint, or build errors and renders",
    async () => {
      const projectId = path.basename(projectDir);
      await generateWriteAndValidate(
        "screen-product-listing",
        "Build a product listing page with a top filter bar (category checkboxes for Electronics, Clothing, Books, Home and a sort dropdown), a grid of 6 product cards (each: image placeholder, name, price, star rating), and prev/next pagination buttons.",
        getScreenNewPrompt("lucide") + outputFilePathSection(fakeOutputPath(projectId)),
        ["input[type='checkbox']"],
      );
    },
    240_000,
  );

  it(
    "generates a settings screen with no type, lint, or build errors and renders",
    async () => {
      const projectId = path.basename(projectDir);
      await generateWriteAndValidate(
        "screen-settings",
        "Build a user settings screen with three tabs: Profile (avatar, name, email, bio fields), Security (current password, new password, 2FA toggle), and Notifications (email and push toggles for different event types). Each tab has a Save button.",
        getScreenNewPrompt("lucide") + outputFilePathSection(fakeOutputPath(projectId)),
        ["input", "button"],
      );
    },
    240_000,
  );

  it(
    "generates a chat messaging screen with no type, lint, or build errors and renders",
    async () => {
      const projectId = path.basename(projectDir);
      await generateWriteAndValidate(
        "screen-chat",
        "Build a messaging screen: left panel is a contacts list with avatars, names, and last message preview. Right panel shows a chat thread with message bubbles from two users, timestamps, and a message input with send button and emoji button at the bottom.",
        getScreenNewPrompt("lucide") + outputFilePathSection(fakeOutputPath(projectId)),
        ["input, textarea"],
      );
    },
    240_000,
  );

  it(
    "generates a SaaS landing page with no type, lint, or build errors and renders",
    async () => {
      const projectId = path.basename(projectDir);
      await generateWriteAndValidate(
        "screen-landing-page",
        "Build a SaaS landing page: sticky nav with logo and CTA button, hero with headline, subheadline and two CTA buttons, features section with 3 cards, pricing section with 3 tiers (Free/Pro/Enterprise), and a simple text footer with copyright. Must be responsive. Do NOT use social media brand icons (Twitter, GitHub, LinkedIn) — they do not exist in lucide-react.",
        getScreenNewPrompt("lucide") + outputFilePathSection(fakeOutputPath(projectId)),
        ["h1, h2", "button"],
      );
    },
    240_000,
  );

  it(
    "edits a generated screen and produces valid code with all checks passing",
    async () => {
      const projectId = path.basename(projectDir);

      // Step 1: Generate a simple initial screen
      const newPrompt =
        getScreenNewPrompt("lucide") + outputFilePathSection(fakeOutputPath(projectId));
      const initial = await generate(
        newPrompt,
        "Build a simple profile page with a user avatar placeholder, full name, email address, and a bio paragraph.",
        12,
        TOOL_CONTEXT,
      );
      expect(initial.primaryContent, "Initial screen generation produced no code.").not.toBeNull();

      await fs.mkdir(testScreenDir, { recursive: true });
      await fs.writeFile(testScreenPath, initial.primaryContent!, "utf8");
      await patchRoutesTs();

      // Step 2: Edit — add an Edit Profile button using the real update prompt with existing code
      const updatePrompt =
        getScreenUpdatePrompt("lucide", initial.primaryContent!) +
        outputFilePathSection(fakeOutputPath(projectId));
      const edited = await generate(
        updatePrompt,
        "Add an 'Edit Profile' button below the bio paragraph.",
        12,
        TOOL_CONTEXT,
      );
      expect(edited.primaryContent, "Edit produced no code.").not.toBeNull();

      await fs.writeFile(testScreenPath, edited.primaryContent!, "utf8");

      const tscOut = runFileTypecheck(previewDir, "src/screens/e2e-test/screen.tsx");
      expect(tscOut, `TypeScript errors after edit:\n${tscOut}`).toBe("");

      const lintOut = filterLintOutput(runLint(previewDir, "src/screens/e2e-test/screen.tsx"));
      expect(lintOut, `ESLint errors after edit:\n${lintOut}`).toBe("");

      runFileBuild(previewDir, "src/screens/e2e-test/screen.tsx");

      const port = BASE_PORT + portOffset++;
      const server = await startDevServer(previewDir, port);
      try {
        const { screenshot, consoleErrors, hasRootContent, missingSelectors } =
          await captureRender(server.url, ["button"]);

        const errors = consoleErrors.filter(
          (e) => !e.includes("favicon") && !e.includes("DevTools"),
        );
        expect(errors, `React errors in edited screen:\n${errors.join("\n")}`).toHaveLength(0);
        expect(hasRootContent, "Edited screen rendered empty").toBe(true);
        expect(
          missingSelectors,
          `Edited screen missing expected elements:\n${missingSelectors.join("\n")}`,
        ).toHaveLength(0);

        const { nonWhiteRatio } = analyzeScreenshot(screenshot);
        expect(nonWhiteRatio, "Edited screen screenshot appears blank").toBeGreaterThan(0.02);

        await saveSnapshot("screen-edit-profile-with-button", screenshot, snapshotDir());
      } finally {
        server.stop();
      }
    },
    300_000,
  );
});
